#!/bin/bash
#PBS -N merge_outliers
#PBS -q workq
#PBS -l select=1:ncpus=4:mem=16gb
#PBS -j oe
#PBS -o merge_outliers.log

cd $PBS_O_WORKDIR

echo "=== PBS MERGE TXT START $(date) ==="

# Micromamba str environment
eval "$(/storage2/matheusbomfim/projects/micromamba/bin/micromamba shell hook --shell bash)"
micromamba activate str

echo "Environment OK: $(bcftools --version | head -1)"

# Execute merge
./outliers_merge.sh
